Anansi: Comms Class Reference
Comms Class Reference
#include <Comms.h>
Public Member Functions
Comms ()
void sendMessage (Message m)
void checkMessages ()
void initialiseNode (std::vector< Port * > serials)
Detailed Description
Definition at line 37 of file Comms.h.
Constructor & Destructor Documentation
Comms::Comms ()
Definition at line 3 of file Comms.cpp.
              {
 }
Member Function Documentation
void Comms::sendMessage (Message m)
Definition at line 6 of file Comms.cpp.
References Message::_targetService, ServiceTable::getService(), handle, Message::readMessage(), PacketHandler::sendPacket(), serviceTable, and Message::toPackets().
{
     vector<packet_t> packets;
     packets = m.toPackets();
     PacketHandler handle;
     byte target = m._targetService;
     Service * s = serviceTable.getService(target);
     if (s -> getShortestDistance() > 0 ) {
         int p = s -> getOutgoingPort();
         for (int i; packets.size() > i; i++) {
             handle.sendPacket(packets[i], p);
         }
     } else {
         m.readMessage();
     }
 }
void Comms::checkMessages ()
Definition at line 27 of file Comms.cpp.
References messageQueue, MessageQueue::popMessage(), MessageQueue::queueSize(), and Message::readMessage().
{
     while (messageQueue.queueSize() > 0) {
         Message message = messageQueue.popMessage();
         message.readMessage();
     }
 }
void Comms::initialiseNode (std::vector< Port * > serials)
Definition at line 35 of file Comms.cpp.
References portList.
{
     portList=serials;
     //portList[3] = *(serials[3]);
     // TODO initialise static variables?
     //int i = 0;
     //while (i < 3){
     //  portList.push_back(*serials[i]);
     //  i++;
     //}
     //for (i = 0; 3 > i ; ++i){// (sizeof(*serials) / sizeof(serials[0])); i++) {
     //  portList[i] = *(serials[i]);
     //}
     // TODO Do resource discovery stuff
 }
The documentation for this class was generated from the following files:
inc/Comms.h
inc/Comms.cpp