Anansi: ServiceTable Class Reference
ServiceTable Class Reference
#include <ServiceTable.h>
Public Member Functions
ServiceTable ()
~ServiceTable ()
Service * getService (byte id)
void addService (Service *s)
void mergeTable (ServiceTable t)
std::map< byte, Service * > getTable ()
string toString ()
Private Attributes
std::map< byte, Service * > _table
Detailed Description
Definition at line 9 of file ServiceTable.h.
Constructor & Destructor Documentation
ServiceTable::ServiceTable ()
Definition at line 3 of file ServiceTable.cpp.
{
 }
ServiceTable::~ServiceTable ()
Definition at line 7 of file ServiceTable.cpp.
{
 }
Member Function Documentation
Service * ServiceTable::getService (byte id)
Definition at line 11 of file ServiceTable.cpp.
References _table.
Referenced by PacketQueue::addPacket(), and Comms::sendMessage().
{
     //printf("got to here");
     fflush(stdout);
     if(_table.size()>id){
         //printf("got to here %d",id);
         fflush(stdout);
     return _table[id];
     }else{ static Service newService(0,"0",false); return &newService;}
 }
void ServiceTable::addService (Service * s)
Definition at line 22 of file ServiceTable.cpp.
References _table, Service::getId(), and Service::getPortMap().
Referenced by mergeTable(), and setup().
{
     int id = s->getId();
     if (_table.find(id) == _table.end()) { // Service is not yet in table
         _table[id] = s;
     } else { // Service is already in table, so merge port maps
         map<int, int> portMap = s->getPortMap();
         for (map<int, int>::iterator it = portMap.begin(); it != portMap.end(); ++it) {
             _table[id]->setPortDistance(it->first, it->second);
         }
     }
 }
void ServiceTable::mergeTable (ServiceTable t)
Definition at line 35 of file ServiceTable.cpp.
References addService(), and getTable().
{
     map<byte, Service*> otherTable = t.getTable();
     for (map<byte, Service*>::iterator it = otherTable.begin(); it != otherTable.end(); ++it) {
         addService(it->second);
     }
 }
map< byte, Service * > ServiceTable::getTable ()
Definition at line 43 of file ServiceTable.cpp.
References _table.
Referenced by mergeTable().
{
     return _table;
 }
string ServiceTable::toString ()
Definition at line 47 of file ServiceTable.cpp.
References _table.
{
     string str = "Table: ";
     for (map<byte, Service*>::iterator it = _table.begin(); it != _table.end(); ++it) {
         str += it->second->getName();
     }
     return str;
 }
Member Data Documentation
std::map<byte, Service*> ServiceTable::_table private
Definition at line 12 of file ServiceTable.h.
Referenced by addService(), getService(), getTable(), and toString().
The documentation for this class was generated from the following files:
inc/ServiceTable.h
inc/ServiceTable.cpp