Anansi: MessageQueue Class Reference
MessageQueue Class Reference
#include <MessageQueue.h>
Public Member Functions
void addMessage (Message m)
void addPriorityMessage (Message m)
deque< Message > getMessageQueue ()
Message popMessage ()
int queueSize ()
Private Attributes
deque< Message > _queue
Detailed Description
Definition at line 6 of file MessageQueue.h.
Member Function Documentation
void MessageQueue::addMessage (Message m)
Definition at line 3 of file MessageQueue.cpp.
References Message::_messageID, and _queue.
Referenced by PortIPAddr::handleData(), and PortPi::read().
{
     // TODO - implement MessageQueue::addMessage
     cout <<"adding message to queue";
     cout <<"/nmessage id:";
     cout << hex <<int(m._messageID);
     _queue.push_back(m);
 }
void MessageQueue::addPriorityMessage (Message m)
Definition at line 11 of file MessageQueue.cpp.
References _queue.
{
     _queue.push_front(m);
 }
deque< Message > MessageQueue::getMessageQueue ()
Definition at line 24 of file MessageQueue.cpp.
References _queue.
{
     return _queue;
 }
Message MessageQueue::popMessage ()
Definition at line 16 of file MessageQueue.cpp.
References _queue.
Referenced by Comms::checkMessages().
{
     // TODO - implement MessageQueue::popMessage
     Message m = _queue.front();
     _queue.pop_front();
     return m;
 }
int MessageQueue::queueSize ()
Definition at line 28 of file MessageQueue.cpp.
References _queue.
Referenced by Comms::checkMessages().
{
     return _queue.size();
 }
Member Data Documentation
deque<Message> MessageQueue::_queue private
Definition at line 8 of file MessageQueue.h.
Referenced by addMessage(), addPriorityMessage(), getMessageQueue(), popMessage(), and queueSize().
The documentation for this class was generated from the following files:
inc/MessageQueue.h
inc/MessageQueue.cpp