Anansi: main_ip_test.cpp File Reference
main_ip_test.cpp File Reference
#include <Comms.h>
#include <unistd.h>
#include <Comms.cpp>
#include <PortIPAddr.cpp>
#include <Port.h>
#include <string>
#include <stdlib.h>
Functions
void setup ()
void loop ()
int main ()
Variables
static std::map< int, int > servicePortMap
static Comms newComms
static PortIPAddr p0 (0)
Function Documentation
void setup ()
Definition at line 22 of file main_ip_test.cpp.
References ServiceTable::addService(), p0, portList, serviceTable, and Service::setPortDistance().
Referenced by main().
              {
     static string service0String ="Service0";
     static string service1String= "Service1";
     static string service2String= "Service2";
     static Service s0(0, service1String,true);
     static Service s1(1, service2String,false); //NEEDS TO BE STATIC !!! once function ends, the object memory will be deallocated otherwise!!!
     static Service s2(2, service2String,false);
     serviceTable.addService(&s0);
     serviceTable.addService(&s1);
     serviceTable.addService(&s2);
     s0.setPortDistance(0,0);
     s1.setPortDistance(0,1);
     s2.setPortDistance(0,2);
     portList.push_back(&p0);
 }
void loop ()
Definition at line 41 of file main_ip_test.cpp.
References p0, and PortIPAddr::write().
Referenced by main().
             {
     vector<byte>  newPacket;
     newPacket.push_back(0xFE);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0x1);
     newPacket.push_back(0xFF);
     newPacket.push_back(0xFE);
   p0.write(newPacket);
 cout <<"Loop";
   usleep(10000);
 }
int main ()
Definition at line 58 of file main_ip_test.cpp.
References loop(), and setup().
           {
 setup();
 while(true){
 loop();
 }
 return 1;
 }
Variable Documentation
std::map<int,int> servicePortMap static
Definition at line 8 of file main_ip_test.cpp.
Comms newComms static
Definition at line 17 of file main_ip_test.cpp.
PortIPAddr p0(0) static
Referenced by loop(), and setup().