Anansi: main.cpp File Reference
main.cpp File Reference
#include <Comms.h>
#include <unistd.h>
#include <Comms.cpp>
#include <PortPi.cpp>
#include <Port.h>
#include <string>
#include <stdlib.h>
Functions
void setup ()
void loop ()
int main ()
Variables
static std::map< int, int > servicePortMap
static Comms newComms
static PortPi p0 (0)
Function Documentation
void setup ()
Definition at line 29 of file main.cpp.
References ServiceTable::addService(), p0, portList, serviceTable, and Service::setPortDistance().
Referenced by main().
              {
     static string service1String ="Service1";
     static string service2String= "Service2";
     static Service s1(0, service1String,true);
     static Service s2(1, service2String,false); //NEEDS TO BE STATIC !!! once function ends, the object memory will be deallocated otherwise!!!
     serviceTable.addService(&s1);
     serviceTable.addService(&s2);
     s1.setPortDistance(0,0);
     s2.setPortDistance(0,1);
     portList.push_back(&p0);
 }
void loop ()
Definition at line 43 of file main.cpp.
References p0, and PortPi::read().
Referenced by main().
             {
   p0.read();
 cout <<"Loop";
   usleep(10000);
 }
int main ()
Definition at line 49 of file main.cpp.
References loop(), and setup().
           {
 setup();
 while(true){
 loop();
 }
 return 1;
 }
Variable Documentation
std::map<int,int> servicePortMap static
Definition at line 15 of file main.cpp.
Comms newComms static
Definition at line 24 of file main.cpp.
PortPi p0(0) static
Referenced by loop(), and setup().