Anansi: piDemo.cpp File Reference
piDemo.cpp File Reference
#include <Comms.h>
#include <unistd.h>
#include <Comms.cpp>
#include <PortIPAddr.cpp>
#include <Port.h>
#include <PortPi.cpp>
#include <string>
#include <stdlib.h>
Functions
void setup ()
void loop ()
int main ()
Variables
static std::map< int, int > servicePortMap
static Comms newComms
static PortIPAddr p0 (0)
static PortPi p1 (1)
Function Documentation
void setup ()
Definition at line 24 of file piDemo.cpp.
References ServiceTable::addService(), p0, p1, portList, serviceTable, and Service::setPortDistance().
Referenced by main().
              {
         static string service0String ="Service0";
         static string service1String ="Service1";
         static string service2String= "Service2";
         static Service s0(0, service0String, false);
         static Service s1(1, service1String, true);
         static Service s2(2, service2String, false); //NEEDS TO BE STATIC !!! once function ends, the object memory will be deallocated otherwise!!!
         serviceTable.addService(&s0);
         serviceTable.addService(&s1);
         serviceTable.addService(&s2);
         s0.setPortDistance(0,1);
         s1.setPortDistance(1,0);
         s2.setPortDistance(1,1);
         portList.push_back(&p0);
         portList.push_back(&p1);
 }
void loop ()
Definition at line 45 of file piDemo.cpp.
References p0, and PortIPAddr::read().
Referenced by main().
             {
   p0.read();
 cout <<"Loop";
   usleep(5000);
 }
int main ()
Definition at line 51 of file piDemo.cpp.
References loop(), and setup().
           {
 setup();
 while(true){
 loop();
 }
 return 1;
 }
Variable Documentation
std::map<int,int> servicePortMap static
Definition at line 9 of file piDemo.cpp.
Comms newComms static
Definition at line 18 of file piDemo.cpp.
PortIPAddr p0(0) static
Referenced by loop(), and setup().
PortPi p1(1) static
Referenced by setup().