Anansi: inc/wiringSerial.c File Reference
wiringSerial.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "wiringSerial.h"
Functions
int serialOpen (const char *device, const int baud)
void serialFlush (const int fd)
void serialClose (const int fd)
void serialPutchar (const int fd, const unsigned char c)
void serialPuts (const int fd, const char *s)
void serialPrintf (const int fd, const char *message,...)
int serialDataAvail (const int fd)
int serialGetchar (const int fd)
Function Documentation
int serialOpen (const char * device, const int baud)
Definition at line 44 of file wiringSerial.c.
References fd.
Referenced by PortPi::PortPi().
 {
   struct termios options ;
   speed_t myBaud ;
   int     status, fd ;
   switch (baud)
   {
     case     50:    myBaud =     B50 ; break ;
     case     75:    myBaud =     B75 ; break ;
     case    110:    myBaud =    B110 ; break ;
     case    134:    myBaud =    B134 ; break ;
     case    150:    myBaud =    B150 ; break ;
     case    200:    myBaud =    B200 ; break ;
     case    300:    myBaud =    B300 ; break ;
     case    600:    myBaud =    B600 ; break ;
     case   1200:    myBaud =   B1200 ; break ;
     case   1800:    myBaud =   B1800 ; break ;
     case   2400:    myBaud =   B2400 ; break ;
     case   4800:    myBaud =   B4800 ; break ;
     case   9600:    myBaud =   B9600 ; break ;
     case  19200:    myBaud =  B19200 ; break ;
     case  38400:    myBaud =  B38400 ; break ;
     case  57600:    myBaud =  B57600 ; break ;
     case 115200:    myBaud = B115200 ; break ;
     case 230400:    myBaud = B230400 ; break ;
     default:
       return -2 ;
   }
   if ((fd = open (device, O_RDWR | O_NOCTTY | O_NDELAY | O_NONBLOCK)) == -1)
     return -1 ;
   fcntl (fd, F_SETFL, O_RDWR) ;
 // Get and modify current options:
   tcgetattr (fd, &options) ;
     cfmakeraw   (&options) ;
     cfsetispeed (&options, myBaud) ;
     cfsetospeed (&options, myBaud) ;
     options.c_cflag |= (CLOCAL | CREAD) ;
     options.c_cflag &= ~PARENB ;
     options.c_cflag &= ~CSTOPB ;
     options.c_cflag &= ~CSIZE ;
     options.c_cflag |= CS8 ;
     options.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG) ;
     options.c_oflag &= ~OPOST ;
     options.c_cc [VMIN]  =   0 ;
     options.c_cc [VTIME] = 100 ;    // Ten seconds (100 deciseconds)
   tcsetattr (fd, TCSANOW | TCSAFLUSH, &options) ;
   ioctl (fd, TIOCMGET, &status);
   status |= TIOCM_DTR ;
   status |= TIOCM_RTS ;
   ioctl (fd, TIOCMSET, &status);
   usleep (10000) ;  // 10mS
   return fd ;
 }
void serialFlush (const int fd)
Definition at line 120 of file wiringSerial.c.
 {
   tcflush (fd, TCIOFLUSH) ;
 }
void serialClose (const int fd)
Definition at line 132 of file wiringSerial.c.
 {
   close (fd) ;
 }
void serialPutchar (const int fd, const unsigned char c)
Definition at line 144 of file wiringSerial.c.
Referenced by PortPi::write(), and Port::write().
 {
   write (fd, &c, 1) ;
 }
void serialPuts (const int fd, const char * s)
Definition at line 156 of file wiringSerial.c.
Referenced by serialPrintf().
 {
   write (fd, s, strlen (s)) ;
 }
void serialPrintf (const int fd, const char * message, ...)
Definition at line 167 of file wiringSerial.c.
References serialPuts().
 {
   va_list argp ;
   char buffer [1024] ;
   va_start (argp, message) ;
     vsnprintf (buffer, 1023, message, argp) ;
   va_end (argp) ;
   serialPuts (fd, buffer) ;
 }
int serialDataAvail (const int fd)
Definition at line 186 of file wiringSerial.c.
Referenced by PortPi::read(), and Port::read().
 {
   int result ;
   if (ioctl (fd, FIONREAD, &result) == -1)
     return -1 ;
   return result ;
 }
int serialGetchar (const int fd)
Definition at line 205 of file wiringSerial.c.
Referenced by PortPi::read(), and Port::read().
 {
   uint8_t x ;
   if (read (fd, &x, 1) != 1)
     return -1 ;
   return ((int)x) & 0xFF ;
 }